### ISSUE TITLE
repo specific updates required

### ISSUE THREAD

**Issue by knitemblazor** [shahkalp09/character-embbeding#1]
tasks.

1. clone the repository make specific changes and push the code into the repo.
2. create a branch named feature_dev/kalp and push the changes
3. in the pycharm terminal 
   type pip freeze create a  requirements.txt commit it and push to the repo

4. push the charcnn notebook as  .py file into the repository
5. try benchmarking the predictions for the shared dataset
6.  try using torch dataloader . by building custom torch dataset
7. create a readme.md (markdown file) for the literature review and push it to the repository

**Comment by knitemblazor** [comment]
tasks.

1. clone the repository make specific changes and push the code into the repo.
2. create a branch named feature_dev/kalp and push the changes

**Comment by knitemblazor** [comment]
@shahkalp09  there are labels in issues which you can use to put issues into categories like

1. question
2. task
3. daily update

**Comment by shahkalp09** [comment]
> @shahkalp09 there are labels in issues which you can use to put issues into categories like
> 
> 1. question
> 2. task
> 3. daily update

ok sir

**Comment by knitemblazor** [comment]
closing as Tasks completed
