### ISSUE TITLE
Guidance for the resolving error

### ISSUE THREAD

**Issue by shahkalp09** [shahkalp09/character-embbeding#5]
Sir, I have uploaded the code-named "cnn_practice_1" for the names and its language dataset using cnn , but I am getting index error-index out of range, tried many times but was not able to resolve that error.Please check the code.

**Comment by knitemblazor** [comment]
@shahkalp09 post the exact error and the line number will connect at 5:30 today.

**Comment by knitemblazor** [comment]
if you have set up the code in pycharm or so you can use the debugger watch a youtube video to use pycharm / python debugger.

**Comment by shahkalp09** [comment]
Ok

**Comment by shahkalp09** [comment]
this two lines are showing error,
__getitem__, cnn_practice_1.py:52;  
cnn_practice_1.py:225

**Comment by knitemblazor** [comment]
from the look of it your entire dataset should be a multiple of your batch size for your given code to work. try duplicating few entries.

**Comment by knitemblazor** [comment]
@shahkalp09  can we schedule the call at 10:00 am  tomorrow.

**Comment by knitemblazor** [comment]
just post an issue with the update for today @shahkalp09

**Comment by knitemblazor** [comment]
will call you on phone once available wont be joining 10 am call @shahkalp09

**Comment by shahkalp09** [comment]
Ok sir

**Comment by shahkalp09** [comment]
I have completed the cnn model with new dataset, have uploaded update , please check.

**Comment by knitemblazor** [comment]
@shahkalp09  if the issue has been resolved you can close this bug

**Comment by shahkalp09** [comment]
Ok sir
