### ISSUE TITLE
Task: 2

### ISSUE THREAD

**Issue by knitemblazor** [shahkalp09/character-embbeding#6]
@shahkalp09 
Build an inference pipeline that is
1. once a text is passed the trained model needs to get loaded and a prediction too has to be made
model.predict("man") = Chinese
2. build the training pipeline such that we can plug in any model and switch between them
3. create a branch named feature_dev/trainer for training flow
4. create a branch named feature_dev/inference for inference flow

**Comment by knitemblazor** [comment]
what you have currently build is a training pipeline similarly we need a prediction flow for an incoming text
@shahkalp09

**Comment by shahkalp09** [comment]
sir, I have uploaded the code with the name suggested, we can predict the language using "(predict_language(input_name))", the accuracy of the model is not good enough but is working end to end. I am working on improving accuracy. pLease check.

**Comment by knitemblazor** [comment]
completed hence closing @shahkalp09
